version: '3.8'

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
